[package]
name = "http-mitm-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
hyper = { version = "1.0.1", features = ["full"] }
tokio = { version = "1.34.0", features = ["full"] }
futures = "0.3.29"
bytes = "1.5.0"
http-body-util = "0.1.0"
pin-project-lite = "0.2.13"
rcgen = "0.11.3"
rustls = "0.21.9"
tokio-rustls = "0.24.1"
tokio-native-tls = "0.3.1"

[dev-dependencies]
axum = { version = "0.6", features = ["ws"] }
reqwest = "0.11.22"
