[package]
name = "http-mitm-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
http = "1.0.0"
httparse = "1.8.0"
hyper = { version = "1.0.1", features = ["full"] }
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full"] }
futures = "0.3.29"
bytes = "1.5.0"
http-body-util = "0.1.0"
pin-project-lite = "0.2.13"

[dev-dependencies]
axum = "0.6"
dashmap = "5.5.3"
reqwest = "0.11.22"
