[package]
name = "http-mitm-proxy"
version = "0.3.0"
description = "A HTTP proxy server library intended to be a backend of application like Burp proxy."
readme = "README.md"
repository = "https://github.com/hatoo/http-mitm-proxy"
edition = "2021"

authors = ["hatoo <hato2000@gmail.com>"]
license = "MIT"
categories = ["network-programming", "web-programming::http-server"]
keywords = ["http", "proxy", "http-proxy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "1.0.1", features = ["full"] }
tokio = { version = "1.34.0", features = ["full"] }
futures = "0.3.29"
bytes = "1.5.0"
http-body-util = "0.1.0"
pin-project-lite = "0.2.13"
rcgen = "0.11.3"
rustls = "0.21.9"
tokio-rustls = "0.24.1"
tokio-native-tls = "0.3.1"
tracing = "0.1.40"
hyper-util = { version = "0.1.1", features = ["tokio"] }

[dev-dependencies]
axum = { version = "0.6", features = ["headers"] }
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
reqwest = "0.11.22"
hyper14 = { package = "hyper", version = "0.14", features = ["full"] }
